# Generated by Django 2.2.16 on 2021-07-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authService', '0002_auto_20210724_1037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
